Python 3.7+ Syntax fix
async is a keyword since py 3.7

https://docs.python.org/3/whatsnew/3.7.html#summary-release-highlights
Backwards incompatible syntax changes:
   async and await are now reserved keywords.

I used the code from the following link as the model for the bugfix

crossbario/autobahn-python#1022

creating /......../env/lib/python3.7/site-packages/indy_plenum_dev-1.6-py3.7.egg

Extracting indy_plenum_dev-1.6-py3.7.egg to /Users/marchon/intaglio/env/lib/python3.7/site-packages
  File "/........../env/lib/python3.7/site-packages/indy_plenum_dev-1.6-py3.7.egg/plenum/common/util.py", line 343
    loop.call_soon(asyncio.async, callback(*args, **kwargs))
                               ^
SyntaxError: invalid syntax

needed to use getattr to get around invalid syntax

Signed-off-by: George (marchon) Lambert <marchon@gmail.com>