async is a keyword since py 3.7
Backwards incompatible syntax changes:

async and await are now reserved keywords.

https://docs.python.org/3/whatsnew/3.7.html#summary-release-highlights

I used the code from the following link as the model for the bugfix
https://github.com/crossbario/autobahn-python/issues/1022

creating /......../env/lib/python3.7/site-packages/indy_plenum_dev-1.6-py3.7.egg

Extracting indy_plenum_dev-1.6-py3.7.egg to /Users/marchon/intaglio/env/lib/python3.7/site-packages
  File "/........../env/lib/python3.7/site-packages/indy_plenum_dev-1.6-py3.7.egg/plenum/common/util.py", line 343
    loop.call_soon(asyncio.async, callback(*args, **kwargs))
                               ^
SyntaxError: invalid syntax

Signed-off-by: George (marchon) Lambert <marchon@gmail.com>